"""``report.md``: a summary table, then one section per bug."""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import Any

from qalab.models.bug import BugReport


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render_markdown(reports: Iterable[BugReport], meta: Mapping[str, Any]) -> str:
    reports = list(reports)
    lines = [
        "# QA Lab triage report",
        "",
        f"Runs: {', '.join(meta.get('run_ids', []))} · clusters: {meta.get('cluster_count', '?')}"
        f" · reports: {len(reports)} · provider: {meta.get('provider') or 'none'}"
        f" · variant: {meta.get('variant', '?')}",
        "",
        "| ID | Priority | Score | Kind | Title | Count | Review |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in reports:
        review = "yes" if r.needs_review else ""
        lines.append(
            f"| {r.id} | {r.priority} | {r.score:g} | {r.kind} | {_cell(r.title)} | "
            f"{r.frequency.count} | {review} |"
        )
    for r in reports:
        lines.extend(_section(r))
    return "\n".join(lines) + "\n"


def _section(r: BugReport) -> list[str]:
    out = [
        "",
        f"## {r.id} · {r.priority} · {r.title}",
        "",
        f"**Component:** {r.component} · **Severity:** {r.severity} · **Score:** {r.score:g}"
        f" · **Seen:** {r.frequency.count}× in {r.frequency.runs} run(s)"
        f" · **Confidence:** {r.confidence:.2f}",
        "",
        r.summary,
        "",
        "**Steps to reproduce**",
        "",
    ]
    for i, step in enumerate(r.steps_to_reproduce, start=1):
        refs = ", ".join(f"{a.run_id}#{a.seq}" for a in step.action_refs or [])
        suffix = f" _({step.source}{': ' + refs if refs else ''})_"
        out.append(f"{i}. {step.text}{suffix}")
    out += [
        "",
        f"**Expected:** {r.expected}",
        "",
        f"**Actual:** {r.actual}",
        "",
        f"**Suspected cause:** {r.suspected_cause}",
        "",
        "**Evidence:** " + ", ".join(f"`{e.run_id}#{e.seq}`" for e in r.evidence),
    ]
    if r.docs_used:
        out.append("")
        out.append("**Docs used:** " + ", ".join(f"`{d}`" for d in r.docs_used))
    if r.attachments:
        out.append("")
        out.append("**Attachments:** " + ", ".join(r.attachments))
    if r.score_breakdown:
        out.append("")
        out.append(
            "**Score breakdown:** " + ", ".join(f"{k}={v:g}" for k, v in r.score_breakdown.items())
        )
    if r.review_reasons:
        out.append("")
        out.append("**Needs review:** " + "; ".join(r.review_reasons))
    g = r.generator
    out.append("")
    out.append(
        f"_Generated by {g.method}"
        + (f" ({g.provider}/{g.model}, {g.prompt_version})" if g.provider else "")
        + (f", attempts={g.attempts}" if g.attempts else "")
        + "_"
    )
    return out
